msg/communities/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.AllCommunities.as_view(), name="list"),
    url(r"^new/$", views.CreateCommunity.as_view(), name="create"),
    url(
        r"^posts/in/(?P<slug>[-\w]+)/$",
        views.SingleCommunity.as_view(),
        name="single"
    ),
    url(
        r"join/(?P<slug>[-\w]+)/$",
        views.JoinCommunity.as_view(),
        name="join"
    ),
    url(
        r"leave/(?P<slug>[-\w]+)/$",
        views.LeaveCommunity.as_view(),
        name="leave"
    ),
    url(
        r"change_status/(?P<slug>[-\w]+)/(?P<user_id>\d+)/(?P<status>\d)/$",
        views.ChangeStatus.as_view(),
        name="change_status"
    ),
]

msg/msg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^communities/",
        include("communities.urls", namespace="communities")),
]

msg/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.AllPosts.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(
        r"by/(?P<username>[-\w]+)/$",
        views.UserPosts.as_view(),
        name="for_user"
    ),
    url(
        r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.SinglePost.as_view(),
        name="single"
    ),
    url(
        r"delete/(?P<pk>\d+)/$",
        views.DeletePost.as_view(),
        name="delete"
    ),
]

msg/templates/index.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block body_content %}
			<div class="landing-header" style="background-image: url('{% static "img/jump.jpg" %}');">
				<div class="container">
					<div class="motto">
						<h1 class="title-uppercase">MSG</h1>
						<h3>The newest social network around!</h3>
						<br />
						<a class="btn" href="#">Sign Up</a>
					</div>
				</div>
			</div>
			<div class="main">
				<div class="section text-center landing-section">
					<div class="container">
						<div class="row">
							<div class="col-md-8 col-md-offset-2">
								<h2>Are you tired of your current social network?</h2>
								<h5>Then join a new one! Nothing's better than starting over!</h5>
								<br />
								<a href="#" class="btn btn-danger btn-fill">Sign Up!</a>
							</div>
						</div>
					</div>
				</div>

				<div class="section section-light-brown landing-section">
					<div class="container">
						<div class="row">
							<div class="col-md-4 column">
								<h4>Messages</h4>
								<p>You can post messages to the network! They'll be seen by other members.</p>
								<a class="btn btn-danger btn-simple" href="#">Sign Up!</a>
							</div>
							<div class="col-md-4 column">
								<h4>Communities</h4>
								<p>Communities are where people with similar interests can have conversations. They're like Twitter's hashtags but different! They're also kind of like sub-Reddits but, hopefully, without the horribleness. Wait, we don't want Twitter's horribleness either. Oh no! We're doomed!</p>
								<a class="btn btn-danger btn-simple" href="#">Sign Up!</a>
							</div>
							<div class="col-md-4 column">
								<h4>You</h4>
								<p>We'll never be able to make a profit on this site unless you give us information we can collect and sell! Do your part today!</p>
								<a class="btn btn-danger btn-simple" href="#">Sign Up!</a>
							</div>
						</div>
					</div>
				</div>
			</div>
{% endblock %}

msg/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'>
		<meta name="viewport" content="width=device-width">
		<title>{% block title_tag %}MSG{% endblock %}</title>
		<!-- fonts -->
		<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

		<!-- stylesheets -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/ct-paper.css' %}">
		<link rel="stylesheet" href="{% static 'css/msg.css' %}">
	</head>
	<body>

		<nav class="navbar navbar-ct-danger navbar-fixed-top" role="navigation" id="navbar">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-2">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">
						<div class="logo-container">
							<div class="logo"><img src="{% static 'img/icons/logo.png' %}"></div>
							<p class="brand">MSG</p>
						</div>
					</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navigation-2">
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
						<li><a href="#" class="btn btn-default btn-fill" data-toggle="modal" data-target="#postModal">Post</a></li>
						<li><a href="{% url 'communities:list' %}" class="btn btn-warning btn-fill">Communities</a></li>
						<li><a href="#" class="btn btn-simple">Log out</a></li>
						{% else %}
						<li><a href="{% url 'posts:all' %}" class="btn btn-simple">Posts</a></li>
						<li><a href="#" class="btn btn-simple">Log in</a></li>
						<li><a href="#" class="btn btn-simple">Sign up</a></li>
						{% endif %}
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-->
		</nav>

		<div class="wrapper {% block wrapper_class %}{% endblock %}">

			{% if messages %}
			<div class="messages">
				{% for message in messages %}
				<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
					<div class="container">{{ message|safe }}</div>
				</div>
				{% endfor %}
			</div>
			{% endif %}

			{% block body_content %}{% endblock %}
		</div>

		<footer class="footer section-dark">
			<div class="container">
				<div class="copyright pull-right">
					&copy; 2016, made with <i class="fa fa-heart heart"></i>
				</div>
			</div>
		</footer>

		{% if user.is_authenticated %}
			{% load post_tags %}
			{% post_form %}
		{% endif %}

		<script src="{% static 'js/jquery-1.10.2.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

		<!--  Plugins -->
		<script src="{% static 'js/ct-paper-checkbox.js' %}"></script>
		<script src="{% static 'js/ct-paper-radio.js' %}"></script>
		<script src="{% static 'js/bootstrap-select.js' %}"></script>
		<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

		<script src="{% static 'js/ct-paper.js' %}"></script>
	</body>
</html>