msg/msg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^communities/",
        include("communities.urls", namespace="communities")),
]

msg/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.AllPosts.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(
        r"by/(?P<username>[-\w]+)/$",
        views.UserPosts.as_view(),
        name="for_user"
    ),
    url(
        r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.SinglePost.as_view(),
        name="single"
    ),
    url(
        r"delete/(?P<pk>\d+)/$",
        views.DeletePost.as_view(),
        name="delete"
    ),
]

msg/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

import misaka

from communities.models import Community


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    community = models.ForeignKey(Community, related_name="posts",
                                  null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

msg/posts/forms.py
from django import forms

from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "community")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["community"].queryset = (
                models.Community.objects.filter(
                    pk__in=user.communities.values_list("community__pk")
                )
            )

msg/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models


class AllPosts(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "community")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_timeline.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class SinglePost(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "community")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, generic.CreateView):
    form_class = forms.PostForm
    model = models.Post

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "community")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Message successfully deleted")
        return super().delete(*args, **kwargs)

msg/posts/templates/posts/_modal.html
{% load bootstrap3 %}
<div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">New post</h4>
			</div>
			<div class="modal-body">
				<form method="POST" action="{% url 'posts:create' %}" id="postForm">
					{% csrf_token %}
					{% bootstrap_form form %}
				</form>
			</div>
			<div class="modal-footer">
				<div class="left-side">
					<button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Never mind</button>
				</div>
				<div class="divider"></div>
				<div class="right-side">
					<input type="submit" value="Post" form="postForm" class="btn btn-primary btn-simple">
				</div>
			</div>
		</div>
	</div>
</div>

msg/posts/templates/posts/_post.html
{% load humanize %}
{% load static from staticfiles %}
<div class="post media">
	<a class="pull-left" href="{% url 'posts:for_user' username=post.user.username %}">
		<div class="avatar">
			<img class="media-object" src="{% static 'img/icons/avatar.png' %}" alt="{{ post.user.username }} avatar">
		</div>
	</a>
	<div class="media-body">
		<strong>{{ post.user.get_short_name }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at|naturaltime }}</a></time>
			{% if post.community %}
			<span class="community-name">in <a href="#">{{ post.community.name }}</a></span>
			{% endif %}
		</h5>
		{{ post.message_html|safe }}
		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

msg/posts/templates/posts/layout.html
{% extends "layout.html" %}

{% block title_tag %}Posts | {{ block.super }}{% endblock %}

{% block wrapper_class %}posts-wrapper{% endblock %}

{% block body_content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block pre_post_content %}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post_content %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

msg/posts/templates/posts/post_confirm_delete.html
{% extends "posts/layout.html" %}

{% block title_tag %}Delete your message? | {{ block.super }}{% endblock %}

{% block post_content %}
<h3>Are you sure you want to delete this message?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Yes, delete it" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Nope, nevermind</a>
</form>

{% endblock %}

msg/posts/templates/posts/post_detail.html
{% extends "posts/layout.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

msg/posts/templates/posts/post_form.html
{% extends "posts/layout.html" %}
{% load bootstrap3 %}

{% block post_content %}
<h4>New post</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

msg/posts/templates/posts/post_list.html
{% extends "posts/layout.html" %}
{% load community_tags %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Communities</h5>
			<ul class="list-unstyled">
				{% get_user_communities as user_communities %}	
				{% for member_community in user_communities %}
				<li class="community li-with-bullet">
					<a href="{% url 'communities:single' slug=member_community.community.slug %}">{{ member_community.community.name }}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Communities</h5>
			<ul class="list-unstyled">
				{% get_other_communities as other_communities %}	
				{% for other_community in other_communities %}
					<li class="community li-with-bullet"><a href="{% url 'communities:single' slug=other_community.slug %}">{{ other_community.name }}</a></li>
				{% endfor %}
			</ul>
			{% if user.is_authenticated %}
			<a href="{% url 'communities:create' %}" class="btn btn-sm btn-fill btn-danger"><span class="glyphicon glyphicon-plus-sign"></span> New community</a>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

msg/posts/templates/posts/user_timeline.html
{% extends "posts/layout.html" %}

{% block pre_post_content %}
<div class="col-md-4">
	<h4>{{ post_user.get_short_name }}</h4>
    <strong>@{{ post_user.username }}</strong>
    {{ post_user.bio }}
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}